### ISSUE TITLE
retain selected filter option

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arcRegistry#6]
https://arcregistry.nfdi4plants.org/arcsearch

After using the filter(s), e.g. `ARC size` + `Bigger than` and searching, the selected filters reset to `Select`. 
Might make life easier to be able to re-select and adapt a filter. (sizeBiggerThan = 200 in first, sizeBiggerThan = 100 in second search)

**Comment by BhanukaRC** [comment]
This issue is fixed and moved to production. This can be closed. @gdoniparthi
