### ISSUE TITLE
Buggy search by arcID

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arcRegistry#9]
https://arcregistry.nfdi4plants.org/arcsearch

Search by arcID 
1. yields a range of ARCs 
2. often throws a 404

**Comment by Brilator** [comment]
the 404 comes mostly when hitting enter rather than clicking "search"

**Comment by BhanukaRC** [comment]
This issue is fixed and moved to production. This can be closed. @gdoniparthi
